name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start Contex with '...'
        2. Register agent with '...'
        3. Publish data '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs here (use `docker compose logs contex` or check application output)
      render: shell

  - type: dropdown
    id: version
    attributes:
      label: Contex Version
      description: What version of Contex are you running?
      options:
        - latest (main branch)
        - 0.2.0
        - 0.1.0
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.11.5"
    validations:
      required: true

  - type: input
    id: redis-version
    attributes:
      label: Redis Version
      description: What version of Redis are you using?
      placeholder: "7.0.12"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (Fedora)
        - Linux (Arch)
        - Linux (Other)
        - macOS
        - Windows
        - Docker
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running Contex?
      options:
        - Docker Compose
        - Docker
        - Local (Python)
        - Kubernetes
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
