name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve. What are you trying to accomplish?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered? Why is this solution better?
      placeholder: "I've considered using... but..."

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be valuable
      placeholder: |
        1. Use case one
        2. Use case two
        3. Use case three
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Small improvement
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to implement this feature?
      options:
        - Yes, I can submit a PR
        - Yes, with guidance
        - No, but I can help test
        - No
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Add any mockups, code examples, or references to similar implementations

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
